### ISSUE TITLE
furniture.3d.io domain

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-furniture-app#1]
host furniture app at https://furniture.3d.io

check out possibilities by preference:
1. github pages
2. ??
3. travis ci deploying to s3 served over cloudfront

**Comment by AVGP** [comment]
Lemme check if GH pages allows custom domain SSL. If it does, it's a deal!

If it doesn't, however, we may as well use travis + S3 + CloudFront

**Comment by AVGP** [comment]
Okay, quick search figured out [that it'll be (3)](https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8) as Github still isn't ready.

However, there's a (2) that I list for completeness but would rather avoid: Cloudflare.
With Cloudflare as the DNS + CDN middleman, we could run our SSL certificate but I'd rather not bring another service into the game, especially as we have an established pipeline for Travis -> S3 -> CloudFront in place.

**Comment by AVGP** [comment]
Done & deployed

**Comment by tomas-polach** [comment]
cool setup!

just realized that we can simplify this a bit further by using github pages as cloudfront origin instead of the s3 bucket:
![aws_cloudfront_management_console](https://user-images.githubusercontent.com/6619499/29001348-fa3a4b92-7a7f-11e7-867f-d3c61f3d6106.jpg)

didn't know this works while writing the issue... it means we don't need s3 and travis :)

**Comment by AVGP** [comment]
woohoo!
