### ISSUE TITLE
Image not uploading and retriving

### ISSUE THREAD

**Issue by vaibhavlinux** [archilogic-com/3dio-furniture-app#6]
how can i upload product and show product plz simply  explain

**Comment by AVGP** [comment]
I'm not sure what you are trying to do.

## If you want to upload a 3D model to use with your own 3d.io application

Right now the furniture API is only exposing our furniture library.
However, here is a video explaining [how to upload your 3D model for 3d.io](https://youtu.be/lF6Qg6tX8uw) in 30 seconds.

## If you try to upload 3D models to the furniture app (https://furniture.3d.io)

That is not possible, as this app is there to let you browse our predefined furniture library.

## If you are trying to convert a 2D floorplan to a 3D model

To get a 3D model from a 2D floorplan, please use [floorplan.3d.io](https://floorplan.3d.io/)

If you have any other question, please let me know!
